name: atx2_env
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.10
  - fastp
  - fastqc
  - star
  - samtools
  - bedtools
  - pandas
  - numpy
  - scikit-learn
  - xgboost
  - shap
  - matplotlib
  - seaborn
  - pybedtools
  - biopython
